import dns from 'dns/promises'
import net from 'net'

/**
 * Self-hosted WordPress (wordpress.org) integration.
 *
 * Auth is an Application Password — generated by the user in their WP profile,
 * used over HTTP Basic. There is no OAuth and no app review, which is why this
 * platform can go live while Meta's review is still pending.
 *
 * The Basic credential (`username:password`, base64) is what we persist in
 * `social_accounts.access_token`, so it drops straight into an Authorization
 * header with no extra column and no re-derivation at publish time. That
 * column is SELECT-revoked for anon and authenticated, so it never reaches a
 * browser.
 */

export class WordPressError extends Error {}

/**
 * The site URL comes from the user and the *server* then fetches it, which is
 * the shape of every SSRF. Resolve the host and refuse anything that lands
 * inside the network the server is sitting in.
 */
function isPrivateAddress(ip: string): boolean {
    if (net.isIPv4(ip)) {
        const [a, b] = ip.split('.').map(Number)
        return (
            a === 0 ||
            a === 10 ||
            a === 127 ||
            (a === 169 && b === 254) ||      // link-local, incl. cloud metadata
            (a === 172 && b >= 16 && b <= 31) ||
            (a === 192 && b === 168) ||
            (a === 100 && b >= 64 && b <= 127) || // carrier-grade NAT
            a >= 224                          // multicast and reserved
        )
    }

    const v6 = ip.toLowerCase()
    if (v6 === '::' || v6 === '::1') return true
    if (v6.startsWith('fe80') || v6.startsWith('fc') || v6.startsWith('fd')) return true
    // IPv4-mapped IPv6, e.g. ::ffff:127.0.0.1
    const mapped = v6.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/)
    if (mapped) return isPrivateAddress(mapped[1])
    return false
}

/**
 * Normalises what the user typed into an origin we are willing to call, or
 * throws a WordPressError whose message is safe to show them.
 */
export async function resolveSiteUrl(input: string): Promise<string> {
    const trimmed = (input || '').trim()
    if (!trimmed) throw new WordPressError('Enter your site address.')

    const withScheme = /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`

    let url: URL
    try {
        url = new URL(withScheme)
    } catch {
        throw new WordPressError('That does not look like a web address.')
    }

    // Application Passwords are refused by WordPress over plain HTTP, so an
    // http:// site would fail later anyway — say so now, and clearly.
    if (url.protocol !== 'https:') {
        throw new WordPressError('Your site must use HTTPS. Application passwords do not work without it.')
    }

    if (url.username || url.password) {
        throw new WordPressError('Remove the username and password from the address.')
    }

    let addresses: { address: string }[]
    try {
        addresses = await dns.lookup(url.hostname, { all: true })
    } catch {
        throw new WordPressError('We could not find that site. Check the address.')
    }

    if (addresses.some((a) => isPrivateAddress(a.address))) {
        throw new WordPressError('That address is not reachable from the internet.')
    }

    return url.origin
}

export function buildBasicCredential(username: string, appPassword: string): string {
    // WordPress shows application passwords in groups of four; it accepts them
    // with or without the spaces, and users paste them either way.
    const password = appPassword.replace(/\s+/g, '')
    return Buffer.from(`${username.trim()}:${password}`, 'utf8').toString('base64')
}

export function wpHeaders(credential: string): Record<string, string> {
    return { Authorization: `Basic ${credential}` }
}

/**
 * Turns a WP REST failure into something a user can act on. WordPress itself
 * returns useful codes; hosts and security plugins mostly return HTML or 403.
 */
export function describeWpFailure(status: number, body: string): string {
    if (status === 401) {
        return 'WordPress rejected those details. Check the username and generate a fresh application password.'
    }
    if (status === 403) {
        return 'WordPress refused the request. A security plugin such as Wordfence is often blocking the REST API.'
    }
    if (status === 404 || /rest_no_route/.test(body)) {
        return 'The WordPress REST API is not reachable at that address. It may be disabled, or the site may not be WordPress.'
    }
    if (status >= 500) {
        return 'Your WordPress site returned an error. Try again in a moment.'
    }
    return 'WordPress rejected the request.'
}
